version: 0.0
os: linux

files:
  # Configure files to be copied from S3 to the EC2 instance
  - source: /
    # Destination on the EC2 instance
    destination: /home/ubuntu/your-directory

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
      # Run scripts/start-server-v1.sh when test v4-using-code-deploy.yml
      # Run scripts/start-server-v2.sh when test v6-using-code-deploy-with-docker.yml
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu