name: Deploy Using EC2

on:
  push:
    branches:
      - v1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 Using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:

          # EC2 host, username, key(pem file)
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          # Fails if any command below fails
          script_stop: true
          script: |
            cd ${{ secrets.EC2_PROJECT_PATH }}
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true  
            nohup java -jar build/libs/*SNAPSHOT.jar >/dev/null 2>&1 &
